### PR TITLE
Container With Most Water

### PR DESCRIPTION
**Pull request by Zaman3027**
https://github.com/dexterpuru/leetcode_cpp/issues/44

### CODE REVIEW

**Comment by dexterpuru** [comment]
@Zaman3027 good job with code, please put link of related issue in the PR description. then you are good to go.

**Comment by Zaman3027** [comment]
Done

**Comment by Zaman3027** [comment]
https://github.com/dexterpuru/leetcode_cpp/issues/44
done

**Review by dexterpuru — APPROVED** [review]

**Comment by dexterpuru** [comment]
@Zaman3027 good job 👍

**Pull request merged**
