### PR TITLE
Solution for Best Time to Buy and Sell Stock II Added

### LINKED ISSUE #31: Best Time to Buy and Sell Stock II
**Question Link**
Link: https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/

Say you have an array prices for which the ith element is the price of a given stock on day i.

Design an algorithm to find the maximum profit. You may complete as many transactions as you like (i.e., buy one and sell one share of the stock multiple times).

Note: You may not engage in multiple transactions at the same time (i.e., you must sell the stock before you buy again).

```
Example 1:

Input: [7,1,5,3,6,4]
Output: 7
Explanation: Buy on day 2 (price = 1) and sell on day 3 (price = 5), profit = 5-1 = 4.
             Then buy on day 4 (price = 3) and sell on day 5 (price = 6), profit = 6-3 = 3.
Example 2:

Input: [1,2,3,4,5]
Output: 4
Explanation: Buy on day 1 (price = 1) and sell on day 5 (price = 5), profit = 5-1 = 4.
             Note that you cannot buy on day 1, buy on day 2 and sell them later, as you are
             engaging multiple transactions at the same time. You must sell before buying again.
Example 3:

Input: [7,6,4,3,1]
Output: 0
Explanation: In this case, no transaction is done, i.e. max profit = 0.
 

Constraints:

1 <= prices.length <= 3 * 10 ^ 4
0 <= prices[i] <= 10 ^ 4
```

### PR DESCRIPTION
**Pull request by MohakChugh**
closes #31

### CODE REVIEW

**Comment by Ak-Shaw** [comment]
@MohakChugh Kindly follow the contribution guidelines. Please do take a look at other folders in the repo for reference. Also, kindly explain the solution approach and/or provide pseudo-code with space and time complexity analysis.

**Comment by MohakChugh** [comment]
@Ak-Shaw I've added the pseudocode, complexity analysis and the approach with the solution. Please review :)

**Review by Ak-Shaw — CHANGES_REQUESTED** [review]
_MaximumDepthOfBinaryTree/maximumDepthOfBinaryTree.cpp_ is not required. Also, kindly take a look at the original repo, the solution is given in a _solution.cpp_ file and the problem statement folder is a sub folder of a topic folder. Kindly make the necessary changes.

**Review by Ak-Shaw — APPROVED** [review]
@MohakChugh Good Job! :rocket: 

BTW, I'll suggest from next time you work on a separate branch and make a pull request to upstream/master from that branch, 'cause that's the traditional workflow of git.

**Pull request merged**
