### PR TITLE
Added solution

### PR DESCRIPTION
**Pull request by manasmhasakar**
Issue #23

### CODE REVIEW

**Comment by dexterpuru** [comment]
@hazard4king kindly add the name of question in the list_of_questions.txt also

**Comment by hazard4king** [comment]
I have added codes and updated questions in .txt from issue no. #23 and #26.

**Comment by Ak-Shaw** [comment]
@hazard4king We have updated the folder structure in our mater branch. Kindly make the necessary changes. Also, from next time, kindly add _only one problem solution per PR_.

**Comment by Ak-Shaw** [comment]
@hazard4king Kindly _update the list_of_questions.txt_ as it currently has merge conflicts.

**Comment by hazard4king** [comment]
> @hazard4king Kindly _update the list_of_questions.txt_ as it currently has merge conflicts.

I have done it now. If you can accept my earlier pull requests I can then switch to a new issue and resolve any further conflicts.

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
@hazard4king Kindly follow the contribution guidelines. Each problem statement folder will contain the solution.cpp and a README.md and will be inside a topic folder. Kindly make the necessary changes. Do take a look into our main repo for reference.

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
Kindly take a look here https://github.com/dexterpuru/leetcode_cpp/tree/master/String/First%20Unique%20Character%20in%20a%20String for reference and make the necessary changes. Also, please add detailed approach and/or pseudo-code, along with time and space complexity analysis.

**Pull request closed without merging**
