### PR TITLE
maximum depth of binary tree solution added

### LINKED ISSUE #30: Maximum Depth of Binary Tree
**Question Link**
https://leetcode.com/problems/maximum-depth-of-binary-tree/
Given a binary tree, find its maximum depth.

The maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.

Note: A leaf is a node with no children.

Example:

Given binary tree [3,9,20,null,null,15,7],
```
    3
   / \
  9  20
    /  \
   15   7
```
return its depth = 3.

### PR DESCRIPTION
**Pull request by MohakChugh**
Closes #30

### CODE REVIEW

**Comment by dexterpuru** [comment]
@MohakChugh please make an issue for the Question before making a PR, follow the format of previously merged issues and PRs.

**Comment by MohakChugh** [comment]
Sure

**Comment by dexterpuru** [comment]
@MohakChugh when i ran your code its giving this error, one should be able to copy-paste and run the code directly from here
Screenshot (171)

**Comment by MohakChugh** [comment]
Okay i'll make the changes

**Comment by MohakChugh** [comment]
Screenshot from 2020-10-01 23-44-44

**Comment by dexterpuru** [comment]
@MohakChugh great work

**Pull request merged**
