### PR TITLE
Add Spiral Matrix Solution

### PR DESCRIPTION
**Pull request by ritik-gupta**
https://github.com/dexterpuru/leetcode_cpp/issues/4

### CODE REVIEW

**Comment by dexterpuru** [comment]
@ritik-gupta please put the link of related issue in the description of PR.

**Comment by ritik-gupta** [comment]
> @ritik-gupta please put the link of related issue in the description of PR.

done

**Comment by dexterpuru** [comment]
Also add the question name in list of questions.

**Comment by dexterpuru** [comment]
When I copied and pasted your solution, i am getting this error, this should not happen, please review it.

Screenshot (169)

**Comment by ritik-gupta** [comment]
check again, i missed something

**Comment by ritik-gupta** [comment]
Screenshot (23)

**Comment by dexterpuru** [comment]
@ritik-gupta omg I am so sorry, I mistakenly ran that code in Java, my bad, you are good to go

**Pull request merged**
